### ISSUE TITLE
Initializing the validator bundle fails

### ISSUE THREAD

**Issue by tvirolai** [NatLibFi/marc-record-validators-melinda#7]
The validators whose factory function expects an argument (sort-keywords.js, ind1-uniq.js) throw an error when trying to initialize the validator bundle.

Here are the stack traces:

```
/home/tvirolai/dev/marc-record-validate-cli/node_modules/@natlibfi/marc-record-validators-melinda/lib/validators/sort-keywords.js:138
        throw new Error("Tag '" + tag + "' is not supported");
        ^

Error: Tag '4' is not supported
    at Object.factory (/home/tvirolai/dev/marc-record-validate-cli/node_modules/@natlibfi/marc-record-validators-melinda/lib/validators/sort-keywords.js:138:15)
    at setupValidator (/home/tvirolai/dev/marc-record-validate-cli/node_modules/@natlibfi/marc-record-validators-melinda/node_modules/@natlibfi/marc-record-validate/lib/main.js:89:53)
    at Array.map (<anonymous>)
    at getValidators (/home/tvirolai/dev/marc-record-validate-cli/node_modules/@natlibfi/marc-record-validators-melinda/node_modules/@natlibfi/marc-record-validate/lib/main.js:92:53)
    at /home/tvirolai/dev/marc-record-validate-cli/node_modules/@natlibfi/marc-record-validators-melinda/node_modules/@natlibfi/marc-record-validate/lib/main.js:121:64
    at Object.<anonymous> (/home/tvirolai/dev/marc-record-validate-cli/build/cli.js:35:58)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
```

For ind1-uniq:

```
/home/tvirolai/dev/marc-record-validate-cli/node_modules/@natlibfi/marc-record-validators-melinda/lib/validators/ind1-uniq.js:73
        throw new Error('Tag is not defined or is not a string');
        ^

Error: Tag is not defined or is not a string
    at Object.factory (/home/tvirolai/dev/marc-record-validate-cli/node_modules/@natlibfi/marc-record-validators-melinda/lib/validators/ind1-uniq.js:73:15)
    at setupValidator (/home/tvirolai/dev/marc-record-validate-cli/node_modules/@natlibfi/marc-record-validators-melinda/node_modules/@natlibfi/marc-record-validate/lib/main.js:89:53)
    at Array.map (<anonymous>)
    at getValidators (/home/tvirolai/dev/marc-record-validate-cli/node_modules/@natlibfi/marc-record-validators-melinda/node_modules/@natlibfi/marc-record-validate/lib/main.js:92:53)
    at /home/tvirolai/dev/marc-record-validate-cli/node_modules/@natlibfi/marc-record-validators-melinda/node_modules/@natlibfi/marc-record-validate/lib/main.js:121:64
    at Object.<anonymous> (/home/tvirolai/dev/marc-record-validate-cli/build/cli.js:35:58)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
```

If these two are disabled, validation works.

**Comment by natlibfi-arlehiko** [comment]
You need to pass the tag as an option to those validators. How are you initializing the bundle?

**Comment by tvirolai** [comment]
Same way as in the example in the readme:

```
import validateFactory from '@natlibfi/marc-record-validators-melinda';

const validate = validateFactory({
  fix: true
});

```

**Comment by natlibfi-arlehiko** [comment]
You can pass the options to the validate factory:
```js
const validate = validateFactory({
  fix: true,
  validators: [{
    name: 'ind1-uniq',
    options: '500'
  }]
});
```
I added the instructions to readme: https://github.com/NatLibFi/marc-record-validators-melinda#passing-options-to-validators
